# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'untitledJRPDCA.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(0, 10, 791, 571))
        self.DFA_tab = QWidget()
        self.DFA_tab.setObjectName(u"DFA_tab")
        self.groupBox = QGroupBox(self.DFA_tab)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(20, 10, 731, 511))
        self.toolBox = QToolBox(self.groupBox)
        self.toolBox.setObjectName(u"toolBox")
        self.toolBox.setGeometry(QRect(10, 30, 211, 461))
        self.tool_box_state = QWidget()
        self.tool_box_state.setObjectName(u"tool_box_state")
        self.tool_box_state.setGeometry(QRect(0, 0, 211, 380))
        self.scrollArea = QScrollArea(self.tool_box_state)
        self.scrollArea.setObjectName(u"scrollArea")
        self.scrollArea.setGeometry(QRect(0, 10, 201, 391))
        self.scrollArea.setWidgetResizable(True)
        self.scrollAreaWidgetContents = QWidget()
        self.scrollAreaWidgetContents.setObjectName(u"scrollAreaWidgetContents")
        self.scrollAreaWidgetContents.setGeometry(QRect(0, 0, 199, 389))
        self.grb_StateName = QGroupBox(self.scrollAreaWidgetContents)
        self.grb_StateName.setObjectName(u"grb_StateName")
        self.grb_StateName.setGeometry(QRect(10, 10, 181, 101))
        self.txt_StateName = QTextEdit(self.grb_StateName)
        self.txt_StateName.setObjectName(u"txt_StateName")
        self.txt_StateName.setGeometry(QRect(20, 30, 141, 31))
        self.btn_add_StateName = QPushButton(self.grb_StateName)
        self.btn_add_StateName.setObjectName(u"btn_add_StateName")
        self.btn_add_StateName.setGeometry(QRect(50, 70, 75, 23))
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.toolBox.addItem(self.tool_box_state, u"State")
        self.page_Alphabet = QWidget()
        self.page_Alphabet.setObjectName(u"page_Alphabet")
        self.page_Alphabet.setGeometry(QRect(0, 0, 211, 380))
        self.scrollArea_2 = QScrollArea(self.page_Alphabet)
        self.scrollArea_2.setObjectName(u"scrollArea_2")
        self.scrollArea_2.setGeometry(QRect(0, 10, 201, 391))
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollAreaWidgetContents_2 = QWidget()
        self.scrollAreaWidgetContents_2.setObjectName(u"scrollAreaWidgetContents_2")
        self.scrollAreaWidgetContents_2.setGeometry(QRect(0, 0, 199, 389))
        self.grb_StateName_2 = QGroupBox(self.scrollAreaWidgetContents_2)
        self.grb_StateName_2.setObjectName(u"grb_StateName_2")
        self.grb_StateName_2.setGeometry(QRect(10, 10, 181, 101))
        self.txt_Alphabet = QTextEdit(self.grb_StateName_2)
        self.txt_Alphabet.setObjectName(u"txt_Alphabet")
        self.txt_Alphabet.setGeometry(QRect(20, 30, 141, 31))
        self.btn_add_Alphabet = QPushButton(self.grb_StateName_2)
        self.btn_add_Alphabet.setObjectName(u"btn_add_Alphabet")
        self.btn_add_Alphabet.setGeometry(QRect(50, 70, 75, 23))
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.toolBox.addItem(self.page_Alphabet, u"Alphabet")
        self.page_Transaction = QWidget()
        self.page_Transaction.setObjectName(u"page_Transaction")
        self.scrollArea_3 = QScrollArea(self.page_Transaction)
        self.scrollArea_3.setObjectName(u"scrollArea_3")
        self.scrollArea_3.setGeometry(QRect(0, 0, 201, 391))
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollAreaWidgetContents_3 = QWidget()
        self.scrollAreaWidgetContents_3.setObjectName(u"scrollAreaWidgetContents_3")
        self.scrollAreaWidgetContents_3.setGeometry(QRect(0, 0, 199, 389))
        self.grb_StateName_3 = QGroupBox(self.scrollAreaWidgetContents_3)
        self.grb_StateName_3.setObjectName(u"grb_StateName_3")
        self.grb_StateName_3.setGeometry(QRect(10, 10, 181, 111))
        self.combo_CurrentStates = QComboBox(self.grb_StateName_3)
        self.combo_CurrentStates.setObjectName(u"combo_CurrentStates")
        self.combo_CurrentStates.setGeometry(QRect(110, 20, 41, 22))
        self.combo_Transactions = QComboBox(self.grb_StateName_3)
        self.combo_Transactions.setObjectName(u"combo_Transactions")
        self.combo_Transactions.setGeometry(QRect(110, 50, 41, 22))
        self.label = QLabel(self.grb_StateName_3)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(20, 20, 71, 16))
        self.combo_TargetStates = QComboBox(self.grb_StateName_3)
        self.combo_TargetStates.setObjectName(u"combo_TargetStates")
        self.combo_TargetStates.setGeometry(QRect(110, 80, 41, 22))
        self.label_2 = QLabel(self.grb_StateName_3)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(20, 50, 71, 16))
        self.label_3 = QLabel(self.grb_StateName_3)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(20, 80, 71, 16))
        self.btn_add_Transaction = QPushButton(self.scrollAreaWidgetContents_3)
        self.btn_add_Transaction.setObjectName(u"btn_add_Transaction")
        self.btn_add_Transaction.setGeometry(QRect(60, 130, 75, 23))
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_3)
        self.toolBox.addItem(self.page_Transaction, u"Transaction:")
        self.tabWidget.addTab(self.DFA_tab, "")
        self.regular_language_tab = QWidget()
        self.regular_language_tab.setObjectName(u"regular_language_tab")
        self.tabWidget.addTab(self.regular_language_tab, "")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)

        self.tabWidget.setCurrentIndex(0)
        self.toolBox.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.groupBox.setTitle("")
        self.grb_StateName.setTitle(QCoreApplication.translate("MainWindow", u"State Name:", None))
        self.btn_add_StateName.setText(QCoreApplication.translate("MainWindow", u"Add", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.tool_box_state), QCoreApplication.translate("MainWindow", u"State", None))
        self.grb_StateName_2.setTitle(QCoreApplication.translate("MainWindow", u"Alphabet:", None))
        self.btn_add_Alphabet.setText(QCoreApplication.translate("MainWindow", u"Add", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_Alphabet), QCoreApplication.translate("MainWindow", u"Alphabet", None))
        self.grb_StateName_3.setTitle(QCoreApplication.translate("MainWindow", u"Transaction", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"current state:", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"transaction:", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"target state:", None))
        self.btn_add_Transaction.setText(QCoreApplication.translate("MainWindow", u"Add", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_Transaction), QCoreApplication.translate("MainWindow", u"Transaction:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.DFA_tab), QCoreApplication.translate("MainWindow", u"DFA", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.regular_language_tab), QCoreApplication.translate("MainWindow", u"Regular Language", None))
    # retranslateUi
